// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using misabarber.Data;

#nullable disable

namespace misabarber.Migrations
{
    [DbContext(typeof(MisaBarberContext))]
    [Migration("20260901213513_AgregarProductos")]
    partial class AgregarProductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("misabarber.Models.AuditoriaGeneral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraEvento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Entidad");

                    b.HasIndex("NegocioId", "FechaHoraEvento");

                    b.ToTable("AuditoriaGeneral");
                });

            modelBuilder.Entity("misabarber.Models.Barbero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Barberos");
                });

            modelBuilder.Entity("misabarber.Models.ChatMensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LeidoPorCliente")
                        .HasColumnType("boolean");

                    b.Property<bool>("LeidoPorStaff")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId", "ClienteId", "FechaEnvio");

                    b.ToTable("ChatMensajes");
                });

            modelBuilder.Entity("misabarber.Models.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("BarberoId", "FechaHora");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("misabarber.Models.CitaAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarberoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraCita")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaHoraEvento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServicioNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("FechaHoraEvento");

                    b.HasIndex("NegocioId");

                    b.ToTable("CitasAuditoria");
                });

            modelBuilder.Entity("misabarber.Models.CitaServicio", b =>
                {
                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("CitaId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("CitaServicios");
                });

            modelBuilder.Entity("misabarber.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("misabarber.Models.HorarioBarbero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberoId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<bool>("Trabaja")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("HorariosBarbero");
                });

            modelBuilder.Entity("misabarber.Models.HorarioNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Abierto")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("HorariosNegocio");
                });

            modelBuilder.Entity("misabarber.Models.Negocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("#2563eb");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ModulosBarbero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Citas,Clientes,Historial");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pro");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("misabarber.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("misabarber.Models.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("misabarber.Models.SuscripcionPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("SuscripcionesPush");
                });

            modelBuilder.Entity("misabarber.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BarberoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("NegocioId", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("misabarber.Models.AuditoriaGeneral", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.Barbero", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.ChatMensaje", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.Cita", b =>
                {
                    b.HasOne("misabarber.Models.Barbero", "Barbero")
                        .WithMany()
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("misabarber.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.CitaAuditoria", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.CitaServicio", b =>
                {
                    b.HasOne("misabarber.Models.Cita", "Cita")
                        .WithMany("CitaServicios")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("misabarber.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("misabarber.Models.Cliente", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.HorarioBarbero", b =>
                {
                    b.HasOne("misabarber.Models.Barbero", "Barbero")
                        .WithMany()
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("misabarber.Models.HorarioNegocio", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.Producto", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.Servicio", b =>
                {
                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.SuscripcionPush", b =>
                {
                    b.HasOne("misabarber.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("misabarber.Models.Usuario", b =>
                {
                    b.HasOne("misabarber.Models.Barbero", "Barbero")
                        .WithMany()
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("misabarber.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("misabarber.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("misabarber.Models.Cita", b =>
                {
                    b.Navigation("CitaServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
